
# I'm not sure why, but for some reason velocity applied to players is different compared to entities and blocks
playerThrowPower: 2.5
entityThrowPower: 2.5
blockThrowPower: 2.5

# Which things should be throwable
playerThrowEnabled: true
entityThrowEnabled: true
blockThrowEnabled: false

# If they are throwable, should players without permissions be able to throw these?
throwPlayersRequiresPermission: false
throwEntitiesRequiresPermission: false
throwBlocksRequiresPermission: false

# Use the old method for handling blocks as entities. This should only be used if my version has bugs, or if your
# server suffers lag problems with large amounts of entities
oldBlockHandling: false

# Allow blocks such as bedrock, end portals, and other strange blocks to be picked up?
breakThingsMode: false