
# I'm not sure why, but for some reason velocity applied to players is different compared to entities and blocks
playerThrowPower: 1.6
entityThrowPower: 1.6
blockThrowPower: 1.6

# Which things should be throwable
playerThrowEnabled: true
entityThrowEnabled: true
blockThrowEnabled: true

# If they are throwable, should players without permissions be able to throw these?
throwPlayersRequiresPermission: false
throwEntitiesRequiresPermission: false
throwBlocksRequiresPermission: false

# Use the old method for handling blocks as entities. This should only be used if my version has bugs, or if your
# server suffers lag problems with large amounts of entities
oldBlockHandling: false
useCustomSounds: false
blockDespawnMinutes: 5
ignoreSpawnProt: false
allowStealing: true

# List of blocks that should not be throwable
blockedBlocks:
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - BEDROCK
  - BARRIER
  - AIR
  - CAVE_AIR
  - VOID_AIR
  - END_PORTAL_FRAME
  - NETHER_PORTAL
  - END_GATEWAY
  - END_PORTAL
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - REINFORCED_DEEPSLATE
  - JIGSAW
  - LIGHT
  - TALL_GRASS
  - TALL_SEAGRASS
  - LARGE_FERN
  - SUNFLOWER
  - LILAC
  - ROSE_BUSH
  - PEONY
  - BIG_DRIPLEAF
  - SMALL_DRIPLEAF
  - PITCHER_PLANT
  - SPAWNER
  - PISTON_HEAD
  - MOVING_PISTON
  - REDSTONE_WIRE
  - WHITE_BED
  - ORANGE_BED
  - MAGENTA_BED
  - LIGHT_BLUE_BED
  - YELLOW_BED
  - LIME_BED
  - PINK_BED
  - GRAY_BED
  - LIGHT_GRAY_BED
  - CYAN_BED
  - PURPLE_BED
  - BLUE_BED
  - BROWN_BED
  - GREEN_BED
  - RED_BED
  - BLACK_BED
  - ACACIA_DOOR
  - BAMBOO_DOOR
  - BIRCH_DOOR
  - CHERRY_DOOR
  - COPPER_DOOR
  - CRIMSON_DOOR
  - DARK_OAK_DOOR
  - EXPOSED_COPPER_DOOR
  - IRON_DOOR
  - JUNGLE_DOOR
  - MANGROVE_DOOR
  - OAK_DOOR
  - OXIDIZED_COPPER_DOOR
  - SPRUCE_DOOR
  - WARPED_DOOR
  - WAXED_COPPER_DOOR
  - WAXED_EXPOSED_COPPER_DOOR
  - WAXED_OXIDIZED_COPPER_DOOR
  - WAXED_WEATHERED_COPPER_DOOR
  - WEATHERED_COPPER_DOOR

# List of entities that should not be throwable
blockedEntities:
  - ITEM
  - ITEM_DISPLAY
  - ITEM_FRAME
  - GLOW_ITEM_FRAME
  - AREA_EFFECT_CLOUD
  - ARROW
  - BREEZE_WIND_CHARGE
  - FIREBALL
  - FIREWORK_ROCKET
  - WITHER_SKULL
  - WIND_CHARGE
  - TEXT_DISPLAY
  - SPECTRAL_ARROW
  - SMALL_FIREBALL
  - SHULKER_BULLET
  - SNOWBALL
  - OMINOUS_ITEM_SPAWNER
  - PAINTING
  - EGG
  - ENDER_PEARL
  - EVOKER_FANGS
  - EXPERIENCE_BOTTLE
  - EXPERIENCE_ORB
  - FISHING_BOBBER
  - LEASH_KNOT
  - LIGHTNING_BOLT
  - LLAMA_SPIT
  - MARKER
  - POTION
  - UNKNOWN