name: Defenestrate
version: '${project.version}'
main: me.pm7.defenestrate.Defenestrate
api-version: 1.21
authors: [ _Pm7 ]
description: "Throw blocks, entities, and your friends!"
commands:
  dsettings:
    description: "Manages the data for the Defenestrate Plugin"
    usage: "/<command> [get|set|list] [setting] [newValue]"
permissions:
  defenestrate.blocks:
    description: "Permission needed for non-ops to pick up and throw blocks if throwBlocksRequiresPermission is true"
  defenestrate.players:
    description: "Permission needed for non-ops to pick up and throw players if throwPlayersRequiresPermission is true"
  defenestrate.entities:
    description: "Permission needed for non-ops to pick up and throw entities if throwEntitiesRequiresPermission is true"
  defenestrate.settings:
    description: "Permission needed for non-ops to change the settings of the plugin via commands"
  defenestrate.all:
    description: "Grants every permission"
    children:
      defenestrate.blocks: true
      defenestrate.players: true
      defenestrate.entities: true
      defenestrate.settings: true